version: '4.30.0'

services:
  lesson1-app:
#    hostname: lesson1-app
    image: demo_docker1:v9
    ports:
      - "8077:8080"
    networks:
      - technest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - technest-pg
  lesson2-app:
#    hostname: lesson2-app
    image: demo2:v10
    ports:
      - "8078:8080"
    networks:
      - technest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - technest-pg
  technest-pg:
    hostname: db
    container_name: technest_docker1
    image: postgres
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - technest
  adminer:
    image: adminer
    ports:
      - "8076:8080"
    networks:
      - technest
  reverse_proxy:
    image: nginx
    hostname: proxy
    container_name: reverse_proxy
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lesson1-app
      - lesson2-app
    networks:
      - technest

#      POSTGRES_DB: technest
#      PGDATA: /data/postgres


volumes:
  db_data: {}
networks:
  technest: