spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/postgres
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pppp}

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true



#    spring:
#      datasource:
#        url: jdbc:postgresql://localhost:5439/exampleDocker
#        username: exampleDocker
#        password: password
server:
  port: 8080
  servlet:
    context-path: /demo2
#        driver-class-name: org.postgresql.Driver